// API Route Constants
export const API_ROUTES = {
    AUTH: {
        BASE: 'auth',
        REGISTER: 'register',
        LOGIN: 'login',
        LOGOUT: 'logout',
        VERIFY_EMAIL: 'verify-email',
        RESEND_VERIFICATION: 'resend-verification',
        SEND_PHONE_OTP: 'send-phone-otp',
        VERIFY_PHONE: 'verify-phone',
        FORGOT_PASSWORD: 'forgot-password',
        RESET_PASSWORD: 'reset-password',
        CHANGE_PASSWORD: 'change-password',
        CHANGE_EMAIL: 'change-email',
        REFRESH_TOKEN: 'refresh-token',
        REFRESH: 'refresh',
        ME: 'me',
        SESSIONS: 'sessions',
        LOGOUT_ALL: 'logout-all',
        GOOGLE: 'google',
        GOOGLE_CALLBACK: 'google/callback',
    },
    USERS: {
        BASE: 'users',
        ME: 'me',
        PROFILE: 'profile',
        UPDATE_PASSWORD: 'update-password',
        DEACTIVATE: 'deactivate',
    },
    PROFILES: {
        BASE: 'profiles',
        BASIC_INFO: 'basic-info',
        COMMUNITY_INFO: 'community-info',
        LOCATION_INFO: 'location-info',
        EDUCATION_INFO: 'education-info',
        FAMILY_INFO: 'family-info',
        LIFESTYLE_INFO: 'lifestyle-info',
        PARTNER_PREFERENCES: 'partner-preferences',
        PHOTOS: 'photos',
        DOCUMENTS: 'documents',
        COMPLETION: 'completion',
        RESUME_JOURNEY: 'resume-journey',
        COMPLETE: 'complete',
        ME: 'me',
    },
    MATCHING: {
        BASE: 'matches',
        RECOMMENDATIONS: 'recommendations',
        SEARCH: 'search',
        FILTERS: 'filters',
        SCORE: 'score',
    },
    CONNECTIONS: {
        BASE: 'connections',
        REQUESTS: 'requests',
        SENT: 'sent',
        RECEIVED: 'received',
        ACCEPT: 'accept',
        REJECT: 'reject',
        CANCEL: 'cancel',
    },
    SHORTLIST: {
        BASE: 'shortlist',
        ADD: 'add',
        REMOVE: 'remove',
        LIST: 'list',
    },
    CHAT: {
        BASE: 'chat',
        CONVERSATIONS: 'conversations',
        MESSAGES: 'messages',
        SEND: 'send',
        MARK_READ: 'mark-read',
    },
    SUBSCRIPTIONS: {
        BASE: 'subscriptions',
        PLANS: 'plans',
        SUBSCRIBE: 'subscribe',
        CANCEL: 'cancel',
        STATUS: 'status',
    },
    PAYMENTS: {
        BASE: 'payments',
        CREATE_ORDER: 'create-order',
        VERIFY: 'verify',
        WEBHOOK: 'webhook',
    },
    ADMIN: {
        BASE: 'admin',
        USERS: 'users',
        PROFILES: 'profiles',
        APPROVE_PHOTO: 'approve-photo',
        REJECT_PHOTO: 'reject-photo',
        REPORTS: 'reports',
        STATISTICS: 'statistics',
    },
} as const;
